trigger:
- master

jobs:

- job: 'Test'
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
        envFile: 'ci/environment-new.yaml'
      windows-32:
        imageName: 'vs2017-win2016'
        envFile: 'ci/environment-new.yaml'
      windows-64:
        imageName: 'vs2017-win2016'
        envFile: 'ci/environment-new.yaml'
      maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: "Add conda to PATH"

  - bash: conda create --yes --quiet --file=$(envFile) --name=dask-ml-test
    displayName: "install"

  - script: |
      conda activate dask-ml-test
      conda list

  - script: |
      conda activate dask-ml-test
      pytest tests
    displayName: 'pytest'

  - script: |
      conda activate dask-ml-test
      echo "[flake8]"
      flake8

      echo "[black]"
      black --check .

      echo "[isort]"
      isort --recursive --check-only .
    displayName: "Lint"

- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python setup.py sdist
    displayName: 'Build sdist'
