trigger:
- master

jobs:
- template: ci/posix.yml
  parameters:
    name: 'linux'
    vmImage: 'ubuntu-16.04'
- template: ci/posix.yml
  parameters:
    name: 'earliest-supported'
    vmImage: 'ubuntu-16.04'
- template: ci/windows.yml
  parameters:
    name: 'win-64'
    vmImage: 'vs2017-win2016'
