name: dask-ml-test
channels:
  - conda-forge
  - defaults
dependencies:
  - coverage
  - distributed==1.25.3
  - dask==1.0.0
  - flake8
  - graphviz
  - heapdict
  - ipython
  - multipledispatch==0.4.9
  - nbsphinx
  - nomkl
  - nose
  - numba
  - numpy==1.15.4
  - numpydoc
  - pandas
  - pandas==0.23.4
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=2.7.*
  - scikit-learn==0.20.0
  - scikit-learn>=0.20.0
  - scipy
  - six
  - sortedcontainers
  - sparse
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - tensorflow
  - testpath<0.4
  - toolz
  - tornado
  - xgboost
  - zict
  - pip:
    - dask-glm
    - git+https://github.com/dask/dask-tensorflow.git
    - git+https://github.com/dask/dask-xgboost.git
    - graphviz
    - pytest-azurepipelines
