name: dask-ml-test
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - coverage
  - codecov
  - flake8
  - graphviz
  - heapdict
  - ipykernel
  - ipython
  - isort
  - multipledispatch
  - nose
  - numba
  - numpy
  - numpydoc
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.7
  - sortedcontainers
  - scikit-learn>=0.20.0
  - scipy
  - six
  - sparse
  - tornado
  - toolz
  - zict
  - pip:
    - dask-glm
    - git+https://github.com/dask/dask.git
    - git+https://github.com/dask/distributed.git
    - graphviz
