name: dask-ml-test
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - coverage
  - codecov
  - flake8
  - graphviz
  - heapdict
  - ipykernel
  - ipython
  - isort
  - multipledispatch
  - nbsphinx
  # - nomkl
  - nose
  - numba
  - numpy
  - numpydoc
  - pandas
  - psutil
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.7.*
  - sortedcontainers
  - scikit-learn>=0.20.0
  - scipy
  - six
  - sparse
  - sphinx
  - sphinx_rtd_theme
  - sphinx-gallery
  - tensorflow
  - testpath<0.4
  - tornado
  - toolz
  - zict
  - dask-glm
  - pip:
    - dask_sphinx_theme >=1.1.0
    - git+https://github.com/dask/dask.git
    - git+https://github.com/dask/distributed.git
    - graphviz
    - pytest-azurepipelines
